org: berabulut
app: project-management-tool
service: project-management-tool-service
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SLS_DEBUG: ${env:SLS_DEBUG}
    DATABASE_URL: ${env:DATABASE_URL}

package:
 individually: false

functions:
  createNewUser:
    handler: handlers/createNewUser.create
    events:
      - http:
          path: user
          method: post
          cors: true
  returnUserData:
    handler: handlers/returnUserData.login
    events:
      - http:
          path: user
          method: get
          cors: true
  createNewBoard:
    handler: handlers/createNewBoard.create
    events:
      - http:
          path: board
          method: post
          cors: true
  returnUserRelatedBoards:
    handler: handlers/returnUserRelatedBoards.boards
    events:
      - http:
          path: userRelatedBoards
          method: post
          cors: true
  returnBoardRelatedUsers:
    handler: handlers/returnBoardRelatedUsers.users
    events:
      - http:
          path: boardRelatedUsers
          method: post
          cors: true
  createNewList:
    handler: handlers/list.create
    events:
      - http:
          path: list
          method: post
          cors: true
  reorderLists:
    handler: handlers/list.reorder
    events:
      - http:
          path: list-reorder
          method: post
          cors: true
  createNewTask:
    handler: handlers/task.create
    events:
      - http:
          path: task
          method: post
          cors: true
  reorderTasks:
    handler: handlers/task.reorder
    events:
      - http:
          path: task-reorder
          method: post
          cors: true
  switchTasks:
    handler: handlers/task.switch
    events:
      - http:
          path: task-switch
          method: post
          cors: true
  returnImages:
    handler: handlers/images.list
    events:
      - http:
          path: list-images
          method: get
          cors: true
  

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
