org: berabulut
app: project-management-tool
service: project-management-tool-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SLS_DEBUG: ${env:SLS_DEBUG}
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  createNewUser:
    handler: handlers/createNewUser.create
    events:
      - http:
          path: createNewUser
          method: post
          cors: true
  returnUserData:
    handler: handlers/returnUserData.login
    events:
      - http:
          path: returnUserData
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin