org: berabulut
app: project-management-tool
service: project-management-tool-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SLS_DEBUG: ${env:SLS_DEBUG}

functions:
  hello:
    handler: handlers/getData.hello
    events:
      - http:
          path: hello
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin